# Data Frames

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/survey_results_public.csv')
schema_df = pd.read_csv('data/survey_results_schema.csv')

In [3]:
# pd.set_option('display.max_rows',87)
pd.set_option('display.max_columns',144)

In [4]:
df.shape

(65437, 114)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

In [6]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [7]:
schema_df

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR
...,...,...,...,...,...,...
82,QID337,JobSatPoints_7,"Learning and using new technology, including p...",NaN,MC,MAVR
83,QID337,JobSatPoints_8,"Designing and building environments, databases...",NaN,MC,MAVR
84,QID337,JobSatPoints_9,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
85,QID337,JobSatPoints_10,Working with new and/or top-quality hardware,NaN,MC,MAVR
86,QID337,JobSatPoints_11,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

In [8]:
# gives all values of column but when using loc for one value it prints the row and for two values it can print the row and column
df['Age']  # or df.loc[:,'Age']

0        Under 18 years old
1           35-44 years old
2           45-54 years old
3           18-24 years old
4           18-24 years old
                ...
65432       18-24 years old
65433       25-34 years old
65434       25-34 years old
65435       18-24 years old
65436       18-24 years old
Name: Age, Length: 65437, dtype: object

In [9]:
df['Age'].value_counts() # gives the counts of differnt values in the column

Age
25-34 years old       23911
35-44 years old       14942
18-24 years old       14098
45-54 years old        6249
55-64 years old        2575
Under 18 years old     2568
65 years or older       772
Prefer not to say       322
Name: count, dtype: int64

In [10]:
df.loc[[0],'Age']

0    Under 18 years old
Name: Age, dtype: object

In [11]:
df.loc[0:3,'Age'] # or df.loc[[0,1,2,3],'Age']

0    Under 18 years old
1       35-44 years old
2       45-54 years old
3       18-24 years old
Name: Age, dtype: object

In [12]:
df.loc[0:3,'Age':'Check'] # similar operations can be done with iloc (df.iloc[0:4,2:6]) except the 2nd values are exclusive

                  Age           Employment RemoteWork   Check
0  Under 18 years old  Employed, full-time     Remote  Apples
1     35-44 years old  Employed, full-time     Remote  Apples
2     45-54 years old  Employed, full-time     Remote  Apples
3     18-24 years old   Student, full-time        NaN  Apples

# Indexes

In [13]:
df.set_index('ResponseId').head() # sets the index to the column 'Respondent'

# df.set_index('ResponseId', inplace=True) # sets the index to the column 'Respondent' and changes the original dataframe

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [14]:
# to change the index while reading the csv file
df = pd.read_csv('data/survey_results_public.csv',index_col='ResponseId')

In [15]:
df.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [16]:
df.loc[1]

MainBranch             I am a developer by profession
Age                                Under 18 years old
Employment                        Employed, full-time
RemoteWork                                     Remote
Check                                          Apples
                                    ...
JobSatPoints_11                                   NaN
SurveyLength                                      NaN
SurveyEase                                        NaN
ConvertedCompYearly                               NaN
JobSat                                            NaN
Name: 1, Length: 113, dtype: object

In [17]:
# what if we want to know the schema of a column without looking at the schema_df
schema_df.set_index('qname')

,qid,question,force_resp,type,selector
qname,,,,,
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Age,QID127,What is your age?*,True,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,True,MC,MAVR
RemoteWork,QID308,Which best describes your current work situation?,False,MC,SAVR
Check,QID341,Just checking to make sure you are paying atte...,True,MC,SAVR
...,...,...,...,...,...
JobSatPoints_7,QID337,"Learning and using new technology, including p...",NaN,MC,MAVR
JobSatPoints_8,QID337,"Designing and building environments, databases...",NaN,MC,MAVR
JobSatPoints_9,QID337,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
JobSatPoints_10,QID337,Working with new and/or top-quality hardware,NaN,MC,MAVR
JobSatPoints_11,QID337,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

In [18]:
# to change index while reading the csv file
schema_df = pd.read_csv('data/survey_results_schema.csv',index_col='qname')

In [19]:
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Age,QID127,What is your age?*,True,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,True,MC,MAVR
RemoteWork,QID308,Which best describes your current work situation?,False,MC,SAVR
Check,QID341,Just checking to make sure you are paying atte...,True,MC,SAVR
...,...,...,...,...,...
JobSatPoints_7,QID337,"Learning and using new technology, including p...",NaN,MC,MAVR
JobSatPoints_8,QID337,"Designing and building environments, databases...",NaN,MC,MAVR
JobSatPoints_9,QID337,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
JobSatPoints_10,QID337,Working with new and/or top-quality hardware,NaN,MC,MAVR
JobSatPoints_11,QID337,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

In [20]:
schema_df.loc['RemoteWork']

qid                                                      QID308
question      Which best describes your current work situation?
force_resp                                                False
type                                                         MC
selector                                                   SAVR
Name: RemoteWork, dtype: object

In [21]:
schema_df.loc['JobSatPoints_9','question'] # use the column name too when the data you need is truncated(not fully displayed)

'Being a power user of a tool, developer language or process that others come to for answers and guidance about'

In [22]:
schema_df.sort_index() # to sort the index (ascending order by default)
schema_df.sort_index(ascending=False) # to sort the index in descending order

,qid,question,force_resp,type,selector
qname,,,,,
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
WorkExp,QID288,How many years of working experience do you have?,False,Slider,HSLIDER
Webframe,QID264,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
ToolsTech,QID275,Which <b>developer </b><strong>tools for compi...,False,Matrix,Likert
...,...,...,...,...,...
AIEthics,QID339,Which AI ethical responsibilities are most imp...,False,MC,MAVR
AIComplex,QID343,How well do the AI tools you use in your devel...,False,MC,SAVR
AIChallenges,QID346,What are the challenges to your company/whole ...,False,MC,MAVR
AIBen,QID324,For the AI tools you use as part of your devel...,False,MC,MAVR
AIAcc,QID316,How much do you trust the accuracy of the outp...,False,MC,SAVR

In [23]:
# for permanent sorting
schema_df.sort_index(inplace=True)
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
AIAcc,QID316,How much do you trust the accuracy of the outp...,False,MC,SAVR
AIBen,QID324,For the AI tools you use as part of your devel...,False,MC,MAVR
AIChallenges,QID346,What are the challenges to your company/whole ...,False,MC,MAVR
AIComplex,QID343,How well do the AI tools you use in your devel...,False,MC,SAVR
AIEthics,QID339,Which AI ethical responsibilities are most imp...,False,MC,MAVR
...,...,...,...,...,...
ToolsTech,QID275,Which <b>developer </b><strong>tools for compi...,False,Matrix,Likert
Webframe,QID264,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
WorkExp,QID288,How many years of working experience do you have?,False,Slider,HSLIDER
YearsCode,QID32,"Including any education, how many years have y...",False,MC,DL
YearsCodePro,QID34,"NOT including education, how many years have y...",False,MC,DL

# Filtering

In [24]:
# to filter salary of people who are making more than a certain amount
high_salary = (df['ConvertedCompYearly'] > 70000)
df.loc[high_salary,['Country','LanguageHaveWorkedWith','ConvertedCompYearly']]

,Country,LanguageHaveWorkedWith,ConvertedCompYearly
ResponseId,,,
380,Turkey,JavaScript;Julia;Python;SQL;TypeScript,91295.0
390,United States of America,HTML/CSS;JavaScript;Python;SQL;TypeScript,110000.0
393,United Kingdom of Great Britain and Northern I...,C#;HTML/CSS;Java;JavaScript;MicroPython;Python...,161044.0
396,United Kingdom of Great Britain and Northern I...,Bash/Shell (all shells);Go;HTML/CSS;Java;Kotli...,121018.0
399,United States of America,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...,195000.0
...,...,...,...
41166,United States of America,F#;SQL,120000.0
41168,United States of America,C#;Dart;HTML/CSS;JavaScript;Solidity;SQL,100000.0
41185,United States of America,Bash/Shell (all shells);C;HTML/CSS;Java;JavaSc...,170000.0
41186,United States of America,C;C#;C++;JavaScript;PowerShell;Python;SQL,116844.0
41188,Switzerland,Assembly;C;C++;Java;Objective-C;PHP;SQL,222834.0

List Filtering

In [25]:
countries = ['United States','India','United Kingdom','Germany','Canada']
filt = df['Country'].isin(countries)
df.loc[filt,['Country']]

            Country
ResponseId
4            Canada
17           Canada
18            India
19          Germany
21          Germany
...             ...
65384         India
65414         India
65416         India
65429         India
65436       Germany

[11282 rows x 1 columns]

In [26]:
df['LanguageHaveWorkedWith']

ResponseId
1                                                      NaN
2        Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
3                                                       C#
4        C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...
5                  C++;HTML/CSS;JavaScript;Lua;Python;Rust
                               ...
65433                                                  NaN
65434                                                  NaN
65435                                                  NaN
65436             C;C++;Go;Lua;Objective-C;Python;Rust;SQL
65437     C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript
Name: LanguageHaveWorkedWith, Length: 65437, dtype: object

String FIltering

In [27]:
filt = df['LanguageHaveWorkedWith'].str.contains('Python',na=False) # na=False to ignore the NaN values
filt

ResponseId
1        False
2         True
3        False
4         True
5         True
         ...
65433    False
65434    False
65435    False
65436     True
65437     True
Name: LanguageHaveWorkedWith, Length: 65437, dtype: bool

In [28]:
df.loc[filt] # here the rows with only True values are displayed

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,NaN,10,NaN,Student,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Cloud Firestore,Cloud Firestore,Cloud Firestore,Cloudflare,Cloudflare,Cloudflare,Node.js,Node.js,Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NaN,NaN,NaN,Docker;Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,iOS;MacOS;Ubuntu,NaN,Markdown File,Markdown File,Markdown File,Discord,Discord,Discord,ChatGPT;GitHub Copilot;OpenAI Codex,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Debugging and getting help,Documenting code;Testing code;Committing and r...,Learning about a codebase;Project planning,NaN,Writing code;Debugging and getting help,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,20,NaN,Project manager,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,JavaScript;Python;Ruby,C#;Crystal;Java;JavaScript;Python;Ruby,JavaScript;Python;Ruby,Elasticsearch;MongoDB;PostgreSQL;SQLite,Elasticsearch;MongoDB;PostgreSQL;SQLite,Elasticsearch;MongoDB;PostgreSQL;SQLite,Amazon Web Services (AWS);Google Cloud,Google Cloud,Google Cloud,Node.js;React;Ruby on Rails,Django;Node.js;React;Ruby on Rails,Node.js;React;Ruby on Rails,NaN,NaN,NaN,NaN,NaN,NaN,Ansible;Docker;Kubernetes,Ansible;Docker;Kubernetes,Ansible;Docker;Kubernetes,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows,Confluence;GitHub Discussions;Jira;Smartsheet,Confluence;GitHub Discussions;Jira,Confluence;GitHub Discussions;Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Microsoft Teams;Slack;Zoom,ChatGPT;GitHub Copilot;Google Gemini;Meta AI;V...,GitHub Copilot;Google Gemini;Visual Studio Int...,GitHub Copilot;Google Gemini;Visual Studio Int...,Stack Overflow for Teams (private knowledge sh...,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Favorable,Increase productivity;Speed up learning;Improv...,Somewhat distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Project planning;Testing code;Generating conte...,Committing and reviewing code;Deployment and m...,NaN,NaN,Learning about a codebase;Writing code;Documen...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,Yes,Individual contributor,15.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,3-5 times a week,6-10 times a week,6-10 times a week,30-60 minutes a day,60-120 minutes a day,Amount of technical debt;Number of software to...,DevOps function;Automated testing;Observabilit...,Cloud only (single or multi-cloud),Internal Developer portal,Healthcare,50.0,0.0,0.0,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65422,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell (all shells);Python,Rust,NaN,PostgreSQL,Dynamodb,NaN,Amazon Web Services (AWS),Amazon Web Services (AWS),Amazon Web Services (AWS),FastAPI,NaN,NaN,NaN,NaN,NaN,mlflow;NumPy;Ruff,NaN,NaN,Pip;Terraform,Pip;Terraform,Pip;Terraform,Sublime Text;Visual Studio Code,Sublime Text;Visual Studio Code,Sublime Text;Visual Studio Code,Windows,Ubuntu,Notion,Notion,Notion,Microsoft Teams,NaN,NaN,ChatGPT,ChatGPT,ChatGPT,Stack Overflow;Stack Exchange,Multiple times per day,Not sure/can't remember,NaN,Quickly finding code solutions;Finding reliabl...,"No, not at all",Yes,Very favorable,Greater efficiency;Speed up learning;Improve a...,Somewhat trust,"Good, but not great at handling complex tasks",Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code,Documenting code;Deployment and monitoring;Pre...,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65428,"I am not primarily a developer, but I write co...",25-34 years old,"Not employed, but looking for work;Employed, p...",In-person,Apples,Hobby;Professional development or self-paced l...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MATLAB;Python;SQL,Bash/Shell (all shells);C;C++;Python;Ruby;SQL,Python;SQL,Microsoft SQL Server;MySQL;PostgreSQL,BigQuery;Cassandra;Databricks SQL;DuckDB;Elast...,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Favorable,Greater efficiency;Speed up learning;Improve a...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Debugging and getting help;Search...,Learning about a codebase;Project planning;Doc...,NaN,NaN,Writing code,Debugging and getting help;Search for answers,NaN,NaN,I'm not sure,Circulating misinformation or disinformation;M...,"AI tools lack context of codebase, internal a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65432,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,38,24,"Developer, full-stack",20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Reputation for quality and ...,Belgium,EUR European Euro,55000.0,Bash/Shell (all shells);C;C#;C++;Delphi;Groovy...,Bash/Shell (all shells);C#;Go;HTML/CSS;Java;Ja...,Bash/Shell (all shells);C#;HTML/CSS;Java;JavaS...,Couch DB;H2;Microsoft SQL Server;MySQL;Oracle;...,Elasticsearch;PostgreSQL;Redis,PostgreSQL,Microsoft Azure,Amazon Web Services (AWS);Firebase;Microsoft A...,Microsoft Azure,Angular;AngularJS;ASP.NET;ASP.NET CORE;Drupal;...,Angular;ASP.NET;ASP.NET CORE;Node.js;Spring Boot,Angular;ASP.NET;ASP.NET CORE;Node.js;Spring Boot,NaN,NaN,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8);Cordova;...,.NET (5+) ;.NET Framework (1.0 - 4.8);Quarkus;...,.NET (5+) ;.NET Framework (1.0 - 4.8);Spring F...,Chocolatey;Docker;Gradle;Homebrew;Kubernetes;n...,Ansible;Chocolatey;Docker;Gradle;Homebrew;Kube...,Chocolatey;Docker;Gradle;Homebrew;Kubernetes;n...,DataGrip;IntelliJ IDEA;PyCharm;Rider;Sublime T...,DataGrip;Fleet;IntelliJ IDEA;PyCharm;Rider;Sub...,DataGrip;IntelliJ IDEA;PyCharm;Rider;Sublime T...,Cygwin;Debian;iOS;iPadOS;MacOS;Ubuntu;Windows;...,Debian;iOS;iPadOS;MacOS;Other Linux-based;Ubun...,Azure Devops;Confluence;Jira;Markdown File;Wikis,Azure Devops;Confluence;Jira;Markdown File;Wikis,Azure Devops;Confluence;Jira;Markdown File;Wikis,Mattermost;Microsoft Teams,Mattermost,Mattermost,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Showcase expert...,"No, not at all","No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,Yes,Individual contributor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,5,2,"Developer, back-end",20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Connected to an open source...,Germany,EUR European Euro,NaN,C;C++;Go;Lua;Objective-C;Python;Rust;SQL,Rust;SQL,Rust;SQL,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,Angular;Node.js;React,NaN,NaN,Arduino;CMake;Cargo;GNU GCC;Rasberry Pi,Cargo;GNU GCC;Rasberry Pi,Cargo;GNU GCC;Rasberry Pi,GTK;OpenGL,NaN,NaN,Ansible;APT;Docker;Make;npm;Pip;Podman,Ansible;APT;Docker;Make;npm;Pip;Podman,Ansible;APT;Docker;Make;npm;Pip;Podman,Vim;Visual Studio Code,Vim;Visual Studio Code,Vim;Visual Studio Code,Android;Other Linux-based;Ubuntu;Windows,Fedora;Other Linux-based;Ubuntu,Confluence;Jira;Markdown File;Obsidian;Trello,Confluence;Jira;Markdown File;Trello,Confluence;Jira;Markdown File;Trello,Discord;Jitsi;Microsoft Teams;Whatsapp,Discord;Jitsi;Whatsapp,Discord;Jitsi;Whatsapp,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions,"No, not really","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript,JavaScript;Python;TypeScript,JavaScript;Python;TypeScript,MongoDB;MySQL;Oracle;PostgreSQL,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Google Cl...,Cloudflare;Google Cloud;Netlify;Vercel,Cloudflare;Google Cloud;Netlify;Vercel,Django;Express;jQuery;Next.js;Node.js;React,Django;Express;Next.js;Node.js;React,Django;Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Pip;Vite,npm;Pip;Vite,npm;Pip;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,MacOS;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Updating Data

In [29]:
# always run the code without using inplace=True ftist to avoid any errors
# if there are no errors then use inplace=True to make the changes permanent
df.rename(columns={'ConvertedCompYearly':'Salary'}, inplace=True)
df['Salary']

ResponseId
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
         ..
65433   NaN
65434   NaN
65435   NaN
65436   NaN
65437   NaN
Name: Salary, Length: 65437, dtype: float64

In [30]:
df['RemoteWork'].value_counts()

RemoteWork
Hybrid (some remote, some in-person)    23015
Remote                                  20831
In-person                               10960
Name: count, dtype: int64

In [31]:
df['RemoteWork'].map({'Hybrid (some remote, some in-person)':'H','Remote':'R','In-person':'I'})

ResponseId
1          R
2          R
3          R
4        NaN
5        NaN
        ...
65433      R
65434      R
65435      I
65436      H
65437    NaN
Name: RemoteWork, Length: 65437, dtype: object

In [32]:
# to set the values of the column permanently
# df['RemoteWork']=df['RemoteWork'].map({'Hybrid (some remote, some in-person)':'H','Remote':'R','In-person':'I'}) 
# # this will cause all the data to become NaN (because there are already undefined values (NaN) in the column) so using replace is a better option here
df['RemoteWork']=df['RemoteWork'].replace({'Hybrid (some remote, some in-person)':'H','Remote':'R','In-person':'I'})
df['RemoteWork'].value_counts()

RemoteWork
H    23015
R    20831
I    10960
Name: count, dtype: int64

# Sorting

In [33]:
df.sort_values(by='Country', inplace=True)
df['Country']
# for removing NaN values 
df['Country'].dropna()

ResponseId
14673    Afghanistan
1378     Afghanistan
33453    Afghanistan
55671    Afghanistan
6942     Afghanistan
            ...
20050       Zimbabwe
23742       Zimbabwe
12040       Zimbabwe
2701        Zimbabwe
1224        Zimbabwe
Name: Country, Length: 58930, dtype: object

In [34]:
df[['Country','Salary']].dropna()

                Country   Salary
ResponseId
14673       Afghanistan   8634.0
6942        Afghanistan   6907.0
25201       Afghanistan      1.0
37549       Afghanistan  11512.0
39346       Afghanistan  20000.0
...                 ...      ...
26497          Zimbabwe  16000.0
31445          Zimbabwe   6000.0
20050          Zimbabwe  18000.0
2701           Zimbabwe  27000.0
1224           Zimbabwe   7200.0

[23435 rows x 2 columns]

In [35]:
# if we want to sort based on the salary also
df.sort_values(by=['Country','Salary'],ascending=[True,False], inplace=True)
df[['Country','Salary']].dropna().head(20)

                Country    Salary
ResponseId
39346       Afghanistan   20000.0
37549       Afghanistan   11512.0
14673       Afghanistan    8634.0
6942        Afghanistan    6907.0
1566        Afghanistan    5940.0
14613       Afghanistan    3597.0
1241        Afghanistan    3279.0
9825        Afghanistan     719.0
38003       Afghanistan      83.0
12281       Afghanistan      14.0
25201       Afghanistan       1.0
22246       Afghanistan       1.0
14311           Albania  107406.0
27873           Albania   64257.0
11267           Albania   64257.0
11575           Albania   64257.0
28182           Albania   48333.0
25187           Albania   35341.0
27693           Albania   23844.0
33016           Albania   21419.0

### nlargest & nsmallest

In [36]:
df['Salary'].nlargest(10) # to get the 10 largest values in the column

ResponseId
15838    16256603.0
12724    13818022.0
28380     9000000.0
17594     6340564.0
17673     4936778.0
19268     3367716.0
23695     2584118.0
33721     2237846.0
34524     2153432.0
13764     2048046.0
Name: Salary, dtype: float64

In [37]:
df.nlargest(10,'Salary') # to get the 10 largest values in the dataframe

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,Salary,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
15838,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...",I,Apples,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,16,5,Project manager,"Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Integrated developer commun...,Ethiopia,ETB\tEthiopian birr,933535410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android;Arch;BSD;ChromeOS;Cygwin;Debian;Fedora...,Android;Arch;BSD;ChromeOS;Cygwin;Debian;Fedora...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,A few times per month or weekly,Yes,A few times per month or weekly,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Highly trust,Very well at handling complex tasks,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,16256603.0,NaN
12724,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",H,Apples,Contribute to open-source projects;Professiona...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;On the job training;Oth...,Blogs;Stack Overflow;Coding sessions (live or ...,NaN,5,10,"Senior Executive (C-Suite, VP, etc.)","10,000 or more employees",I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Is set up to be customized and needs to be eng...,APIs;Customization;Integrated developer commun...,South Africa,ZAR\tSouth African rand,256800347.0,C++;HTML/CSS;Java;JavaScript;Kotlin;Objective-...,Ada;Apex;Go;Solidity;TypeScript;Zig,NaN,Firebase Realtime Database;IBM DB2;Microsoft A...,BigQuery;Cassandra;Cloud Firestore;Cockroachdb...,NaN,Digital Ocean;Firebase;Fly.io;Netlify;OpenStac...,Alibaba Cloud;Amazon Web Services (AWS);Coloca...,Oracle Cloud Infrastructure (OCI),Blazor;Express;Node.js;WordPress,Astro;Django;Gatsby;jQuery;Laravel;Next.js;Pho...,NaN,NaN,NaN,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8);DirectX;...,.NET MAUI;Apache Spark;Cordova;Hadoop;JAX;Open...,NaN,Ant;Composer;Google Test;Ninja;NuGet;Pacman;Te...,Ant;Bun;Composer;Gradle;Make;Maven (build tool...,Ant;Composer;Visual Studio Solution,Android Studio;Kate;Notepad++;Qt Creator;Visua...,Android Studio;Eclipse;RStudio;Spyder,Android Studio,Arch;Cygwin;Fedora;Other Linux-based;Ubuntu;Wi...,Android;iOS;iPadOS;MacOS;Red Hat;Solaris;Windows,Basecamp;Clickup;Lucid;Monday.com;Redmine;Stac...,Airtable;Asana;Azure Devops;Confluence;GitHub ...,NaN,Discord;Google Chat;Google Meet;Microsoft Team...,Cisco Webex Teams;Coolfire Core;IRC;Matrix;Roc...,NaN,ChatGPT;Google Gemini;Meta AI;Neeva AI;Visual ...,AskCodi;Amazon Q;GitHub Copilot;Lightning AI;P...,Visual Studio Intellicode,Stack Overflow for Teams (private knowledge sh...,Less than once per month or monthly,Yes,A few times per month or weekly,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Indifferent,Increase productivity;Greater efficiency;Impro...,Highly trust,Very well at handling complex tasks,Learning about a codebase,Project planning;Writing code;Documenting code...,NaN,NaN,NaN,Learning about a codebase,NaN,NaN,Yes,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,Yes,People manager,4.0,Agree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Amount of technical debt;Number of software to...,DevOps function;Automated testing;Observabilit...,Hybrid (on-prem and cloud),Traditional public search engine,Media & Advertising Services,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,Appropriate in length,Neither easy nor difficult,13818022.0,10.0
28380,I am a developer by profession,18-24 years old,"Employed, full-time",H,Apples,Contribute to open-source projects,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;On the job training;Oth...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,15,7,Hardware Engineer,"10,000 or more employees",I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,Customization;Integrated developer community;R...,Taiwan,USD\tUnited States dollar,9000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Red Hat,Arch;Fedora;iOS;MacOS;Other Linux-based,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions,"Yes, definitely","No, but I plan to soon",Unsure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,Yes,Individual contributor,15.0,Strongly agree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Agree,Strongly agree,Strongly agree,1-2 times a week,1-2 times a week,Never,60-120 minutes a day,60-120 minutes a day,Amount of technical debt,DevOps function;Automated testing;Observabilit...,Hybrid (on-prem and cloud),Traditional public search engine,Computer Systems Design and Services,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,Appropriate in length,Neither easy nor difficult,9000000.0,10.0
17594,I am a developer by profession,35-44 years old,"Employed, full-time",R,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Oth...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,16,13,"Developer, back-end",20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Out-of-the-box is ready to go with little need...,APIs;Customization;Integrated developer commun...,Brazil,BRL\tBrazilian real,34000000.0,Elixir;Ruby,Elixir;Go;Kotlin;Ruby,Elixir;Ruby,MySQL;PostgreSQL,PostgreSQL;SQLite,PostgreSQL,Amazon Web Services (AWS);Heroku,Amazon Web Services (AWS);Fly.io;Heroku;Supabase,Amazon Web Services (AWS);Heroku,Phoenix;Ruby on Rails,Phoenix;Ruby on Rails,Phoenix;Ruby on Rails,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew,Docker;Homebrew;Nix,Docker;Homebrew,Neovim;Visual Studio Code,Neovim;Xcode,Neovim,Android;iPadOS;MacOS,MacOS,Basecamp;Jira;Miro;Obsidian,GitHub Discussions;Obsidian,Obsidian,Google Meet;Slack,Google Meet;Slack,Google Meet;Slack,ChatGPT,ChatGPT;GitHub Copilot;Google Gemini,ChatGPT,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Finding reliabl...,"No, not really","No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;B...,Don’t trust the output or answers,Yes,Individual contributor,13.0,Strongly agree,Agree,Disagree,Disagree,Disagree,Agree,Strongly agree,Disagree,Strongly disagree,3-5 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Amount of technical debt;Showing my contributi...,DevOps function;Automated testing;Observabilit...,Cloud only (single or multi-cloud),A coworker,Software Development,30.0,0.0,60.0,75.0,40.0,30.0,40.0,30.0,70.0,Appropriate in length,Easy,6340564.0,6.0
17673,I am a developer by profession,25-34 years old,"Employed, full-time",R,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;V...,API document(s) and/or SDK document(s);User gu...,16,11,"Developer, mobile","1,000 to 4,999 employees",I have little or no influence,NaN,Is ready-to-go but also customizable for growt...,NaN,Ukraine,UAH\tUkrainian hryvnia,200000000.0,Objective-C;Swift,Objective-C;Swift,Objective-C;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SwiftUI,SwiftUI,SwiftUI,NaN,NaN,NaN,Xcode,Xcode,Xcode,iOS;MacOS,iOS;MacOS,Confluence;Jira,Confluence;Jira,Confluence;Jira,Microsoft Teams,Microsoft Teams,Microsoft Teams,NaN,NaN,NaN,Stack Overflow,A few times per week,No,NaN,Quickly finding code solutions;Learning new-to...,Neutral,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,11.0,Agree,Neither agree nor disagree,Agree,Strongly agree,Strongly agree,Disagree,Disagree,Agree,Disagree,NaN,NaN,NaN,30-60 minutes a day,30-60 minutes a day,Patching/updating core components;Reliability ...,DevOps function;Automated testing;Knowledge sh...,Hybrid (on-prem and cloud),Traditional public search engine,Software Development,10.0,0.0,0.0,25.0,35.0,20.0,10.0,0.0,0.0,Too long,Neither easy nor difficult,4936778.0,7.0
19268,I am a developer by profession,25-34 years old,"Employed, full-time",I,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Blogs;Books;Written Tutorials;Stack Overflow;C...,NaN,13,7,"Developer, front-end","1,000 to 4,999 employees",I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Integrated developer commun...,India,INR\tIndian rupee,281500000.0,HTML/CSS;JavaScript;SQL,HTML/CSS;JavaScript;Python;Rust;TypeScript;Zig,HTML/CSS;JavaScript,BigQuery;Elasticsearch;MongoDB;MySQL;Redis;Sup...,MongoDB;MySQL;Redis;Supabase,MongoDB;MySQL;Redis;Supabase,Amazon Web Services (AWS);Firebase;Google Clou...,Google Cloud;Supabase;Vercel,Google Cloud;Supabase,Express;Next.js;Node.js;React,Deno;Htmx;NestJS;Next.js;Node.js;Nuxt.js;React...,Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Kubernetes;npm;Vite;Webpack;Yarn,npm;pnpm;Vite;Yarn,npm;Vite;Yarn,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,Confluence;Jira;Notion;Trello,Miro;Notion,Notion,Google Meet,Google Meet,Google Meet,ChatGPT;Google Gemini,ChatGPT;GitHub Copilot,ChatGPT,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"No, not really",Yes,Favorable,Increase productivity;Greater efficiency;Impro...,Neither trust nor distrust,Very poor at handling complex tasks,Search for answers;Generating content or synth...,Learning about a codebase;Project planning;Wri...,Deployment and monitoring;Predictive analytics,NaN,NaN,Search for answers;Generating content or synth...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,Yes,Individual contributor,7.0,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,Disagree,Strongly agree,Neither agree nor disagree,Agree,6-10 times a week,6-10 times a week,1-2 times a week,60-120 minutes a day,60-120 minutes a day,Amount of technical debt,DevOps function;Knowledge sharing community;Mi...,Cloud only (single or multi-cloud),Traditional public search engine,Other:,20.0,0.0,0.0,20.0,30.0,30.0,0.0,0.0,0.0,Appropriate in length,Easy,3367716.0,7.0
23695,I am a developer by profession,18-24 years old,"Employed, full-time;Independent contractor, fr...",R,Apples,Freelance/contract work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",On the job training;Other online resources (e....,Technical documentation;Written Tutorials;Writ...,API document(s) and/or SDK document(s);User gu...,9,5,"Developer, desktop or enterprise applications","1,000 to 4,999 employees",I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Out-of-the-box is ready to go with little need...,APIs;Quality support system;Reputation for qua...,Pakistan,PKR\tPakistani rupee,720000000.0,Ada;Apex;C;C#;HTML/CSS;JavaScript;Kotlin;Python,HTML/CSS;JavaScript;Python,HTML/CSS;JavaScript;Python,BigQuery;Firebase Realtime Database;Microsoft ...,Firebase Realtime Database;Microsoft SQL Serve...,Firebase Realtime Database;Microsoft SQL Serve...,Amazon Web Services (AWS);Cloudflare;Databrick...,Databricks;Firebase;VMware,Databricks;Firebase,Angular;AngularJS;Django;FastAPI;Fastify;Flask...,AngularJS;jQuery;Node.js;Svelte,AngularJS;jQuery;Node.js,Arduino;GNU GCC;LLVM's Clang;Rasberry Pi,GNU GCC;LLVM's Clang,GNU GCC;LLVM's Clang,.NET (5+) ;Apache Kafka;Apache Spark;CUDA;Dire...,CUDA;DirectX;Flutter,CUDA;DirectX;Flutter,Ansible;APT;Bun;Chocolatey;Dagger;Docker;Gradl...,APT;Docker;Gradle;npm;Pacman;Pip,APT;Docker;Gradle;npm;Pacman;Pip,Android Studio;IntelliJ IDEA;Jupyter Notebook/...,Nano;Visual Studio;VSCodium,Nano;Visual Studio,Android;Arch;MacOS;Windows;Windows Subsystem f...,Android;Arch;MacOS;Windows;Windows Subsystem f...,Azure Devops;Clickup;GitHub Discussions;Jira;M...,Azure Devops;Jira;Markdown File;Miro,Azure Devops;Jira;Markdown File;Miro,Cisco Webex Teams;Discord;Google Chat;Google M...,Cisco Webex Teams;Discord;Google Chat;Google M...,Cisco Webex Teams;Discord;Google Chat;Google M...,Andi;Amazon Q;Bing AI;ChatGPT;Codeium;GitHub C...,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow;Stack Exchange;Stack Overflow B...,A few times per month or weekly,No,NaN,Quickly finding code solutions;Finding reliabl...,Neutral,Yes,Indifferent,Increase productivity;Make workload more manag...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Documenting code;Deployment and m...,Project planning;Debugging and getting help;Te...,Learning about a codebase;Generating content o...,NaN,Writing code;Documenting code;Deployment and m...,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,2584118.0,NaN
33721,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...",R,Apples,Contribute to open-source projects;Freelance/c...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague,NaN,NaN,9,5,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,Reputation for quality and excellence;Frequent...,Brazil,BRL\tBrazilian real,12000000.0,HTML/CSS;JavaScript;TypeScript,JavaScript;Rust;TypeScript,JavaScript;TypeScript,Dynamodb,Dynamodb;PostgreSQL;Supabase,Dynamodb,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS);Microsoft Azure,Amazon Web Services (AWS),Next.js;Node.js;React,React,React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;npm;pnpm;Vite,Docker;pnpm;Vite,Docker;pnpm;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),Markdown File;Notion,GitHub Discussions;Markdown File,Markdown File,Discord;Slack;Whatsapp,Discord;Slack;Whatsapp,Discord;Slack;Whatsapp,Amazon Q;ChatGPT;GitHub Copilot,Amazon Q;ChatGPT;GitHub Copilot;Google Gemini,Amazon Q;ChatGPT;GitHub Copilot,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions,"Yes, somewhat",Yes,Indifferent,Make workload more manageable,Neither trust nor distrust,Neither good or bad at handling complex tasks,Documenting code;Debugging and getting help;Te...,Project planning;Writing code;Committing and r...,Learning about a codebase,Testing code,Debugging and getting help,Generating content or synthetic data,NaN,Documenting code,No,Circulating misinformation or disinformation;M...,"AI tools lack context of codebase, internal a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,2237846.0,NaN

In [38]:
df.nsmallest(5,'Salary') # to get the 5 smallest values in the dataframe

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,Salary,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
25201,"I am not primarily a developer, but I write co...",18-24 years old,"Not employed, but looking for work;Independent...",H,Apples,Professional development or self-paced learnin...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Written Tutorials;Coding sessions (live or rec...,NaN,NaN,NaN,Blockchain,500 to 999 employees,I have a great deal of influence,Read ratings or reviews on third party sites l...,Is ready-to-go but also customizable for growt...,APIs;Customization;Integrated developer commun...,Afghanistan,ANG Netherlands Antillean guilder,2.0,MicroPython,Ada,NaN,BigQuery,BigQuery,BigQuery,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Cloudflare;Databrick...,Amazon Web Services (AWS),NaN,NaN,NaN,Arduino,Arduino,Arduino,.NET (5+),.NET (5+),.NET (5+),NaN,NaN,NaN,Android Studio,Android Studio,Android Studio,AIX,AIX,Airtable,Airtable,Airtable,Cisco Webex Teams,Cisco Webex Teams,Cisco Webex Teams,Amazon Q,Amazon Q,Amazon Q,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,"No, but I plan to soon",Indifferent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,Missing or incorrect attribution for sources o...,"AI tools lack context of codebase, internal a...",Yes,People manager,17.0,Agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,NaN,NaN,10+ times a week,10+ times a week,10+ times a week,Over 120 minutes a day,Over 120 minutes a day,Amount of technical debt;Number of software to...,DevOps function;Automated testing;Observabilit...,Hybrid (on-prem and cloud),Internal Developer portal,Software Development,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,1.0,10.0
22246,I am a developer by profession,65 years or older,"Independent contractor, freelancer, or self-em...",I,Apples,Professional development or self-paced learnin...,Primary/elementary school,"Other online resources (e.g., videos, blogs, f...",Books,NaN,More than 50 years,More than 50 years,Data engineer,I don’t know,I have little or no influence,Ask a generative AI tool,Out-of-the-box is ready to go with little need...,Connected to an open source project,Afghanistan,AFN\tAfghan afghani,45.0,C;C++;Elixir;Go;HTML/CSS;Java;JavaScript;Power...,JavaScript;Rust,JavaScript;Rust,SQLite,Cockroachdb,NaN,Oracle Cloud Infrastructure (OCI),Oracle Cloud Infrastructure (OCI),Oracle Cloud Infrastructure (OCI),Node.js;Vue.js,Node.js,Node.js,Cargo;GNU GCC;LLVM's Clang;SCons,Cargo;GNU GCC;LLVM's Clang;MSVC;SCons,Cargo;GNU GCC;LLVM's Clang;SCons,NaN,NaN,NaN,Make;Maven (build tool);npm;Webpack,Docker,NaN,Helix;Vim,NaN,NaN,BSD;Cygwin;iOS;iPadOS;Windows,BSD;iOS;iPadOS;Red Hat;Windows,Markdown File;Wikis,Markdown File;Wikis,Markdown File;Wikis,Matrix,Matrix,Matrix,Bing AI;ChatGPT;Google Gemini;You.com,Bing AI;Google Gemini;WolframAlpha,Bing AI;Google Gemini,Stack Overflow,Less than once per month or monthly,Yes,Less than once per month or monthly,NaN,"No, not at all","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,1.0,NaN
6103,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...",R,Apples,Hobby;Bootstrapping a business;Freelance/contr...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Friend or family member,NaN,NaN,5,3,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,Start a free trial,Is ready-to-go but also customizable for growt...,Frequent updates to features;Connected to an o...,Colombia,COP\tColombian peso,4330.0,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Swift;TypeScript,HTML/CSS;JavaScript;TypeScript,MongoDB;PostgreSQL;Redis,MongoDB;PostgreSQL;Redis;Supabase,MongoDB;PostgreSQL;Redis,Netlify,Netlify;Vercel,Netlify,Angular;Express;NestJS;Next.js;Node.js;React,Angular;Astro;Express;NestJS;Next.js;Node.js;R...,Angular;Express;NestJS;Next.js;Node.js;React,NaN,NaN,NaN,Ionic,NaN,NaN,npm;Vite;Webpack,Godot;npm;Unity 3D;Vite;Webpack,npm;Vite;Webpack,Android Studio;Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,Ubuntu,GitHub Discussions;Notion,GitHub Discussions;Notion,GitHub Discussions;Notion,Discord;Whatsapp,Discord,Discord,ChatGPT;Claude;Google Gemini,ChatGPT;Claude;GitHub Copilot;Google Gemini,ChatGPT;Claude;Google Gemini,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions,"No, not at all",Yes,Favorable,Increase productivity;Speed up learning;Improv...,Neither trust nor distrust,Bad at handling complex tasks,Writing code;Documenting code;Debugging and ge...,Learning about a codebase;Testing code;Generat...,Project planning;Deployment and monitoring;Pre...,Writing code;Documenting code;Debugging and ge...,NaN,Committing and reviewing code,NaN,NaN,I'm not sure,Circulating misinformation or disinformation;M...,"AI tools lack context of codebase, internal a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,1.0,NaN
3891,I am a developer by profession,25-34 years old,"Employed, full-time",I,Apples,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials,API document(s) and/or SDK document(s),13,6,"Developer, full-stack","1,000 to 4,999 employees",I have little or no influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Reputation for quality and ...,France,EUR European Euro,1.0,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;JavaScript;Po...,Bash/Shell (all shells);HTML/CSS;JavaScript;Po...,MySQL;Oracle,NaN,NaN,OpenShift,OpenShift,OpenShift,Angular;Vue.js,Angular;Vue.js,Angular;Vue.js,NaN,NaN,NaN,Spring Framework,NaN,NaN,Godot;Maven (build tool);Vite,Godot;Vite,Godot;Vite,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Vim;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,Windows,Windows,Jira,NaN,NaN,Microsoft Teams,Slack,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"No, not really","No, but I plan to soon",Indifferent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,Circulating misinformation or disinformation;M...,Lack of proper training and education on new t...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,1.0,NaN
26674,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",H,Apples,Bootstrapping a business;Professional developm...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Stack Overflow;How-to videos;Video-based Onlin...,NaN,10,10,"Developer, full-stack",20 to 99 employees,I have some influence,Start a free trial;Ask a generative AI tool;Vi...,Is ready-to-go but also customizable for growt...,APIs;Customization;Integrated developer commun...,Germany,EUR European Euro,1.0,C#;Go;HTML/CSS;Java;JavaScript;PHP;SQL;TypeScript,C#;HTML/CSS;Java;JavaScript;SQL;TypeScript,C#;HTML/CSS;Java;JavaScript;SQL;TypeScript,MariaDB;Microsoft SQL Server;MongoDB;MySQL;SQLite,MariaDB;Microsoft SQL Server;MongoDB;MySQL;SQLite,MariaDB;Microsoft SQL Server;MongoDB;MySQL;SQLite,Amazon Web Services (AWS);Cloudflare;Microsoft...,Amazon Web Services (AWS);Cloudflare;Microsoft...,Amazon Web Services (AWS);Cloudflare;Microsoft...,Angular;AngularJS;ASP.NET;ASP.NET CORE;Express...,Angular;AngularJS;ASP.NET;ASP.NET CORE;Express...,Angular;AngularJS;ASP.NET;ASP.NET CORE;Express...,NaN,NaN,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8);Capacito...,.NET (5+) ;.NET Framework (1.0 - 4.8);Capacito...,.NET (5+) ;.NET Framework (1.0 - 4.8);Capacito...,Ansible;Docker;Homebrew;Kubernetes;npm;NuGet;T...,Docker;Homebrew;Kubernetes;npm;NuGet;Terraform...,Docker;Homebrew;Kubernetes;npm;NuGet;Terraform...,DataGrip;Eclipse;IntelliJ IDEA;Netbeans;Notepa...,IntelliJ IDEA;Visual Studio Code;WebStorm,IntelliJ IDEA;Visual Studio Code;WebStorm,iOS;Windows,MacOS,Confluence;Jira;Miro;Notion;Trello,Confluence;Jira;Miro,Confluence;Jira;Miro,Microsoft Teams;Slack,Microsoft Teams;Slack,Microsoft Teams;Slack,ChatGPT;Google Gemini,ChatGPT;Google Gemini,ChatGPT;Google Gemini,Stack Overflow;Stack Exchange;Stack Overflow B...,A few times per week,Yes,A few times per month or weekly,Quickly finding code solutions,"Yes, somewhat",Yes,Indifferent,Improve collaboration,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Documenting code,Writing code;Testing code;Committing and revie...,Project planning;Debugging and getting help;Pr...,NaN,NaN,Learning about a codebase;Documenting code,NaN,NaN,No,Missing or incorrect attribution for sources o...,Lack of executive buy-in;Not everyone uses them,Yes,Individual contributor,10.0,Agree,Disagree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,1-2 times a week,6-10 times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Tracking my work;Reliability of tools/systems ...,Observability tools,Hybrid (on-prem and cloud),Traditional public search engine,Software Development,40.0,30.0,30.0,40.0,50.0,50.0,50.0,40.0,50.0,Too long,Neither easy nor difficult,1.0,6.0

# Grouping & Aggregating Data

### Functions

In [39]:
df['Salary'].head(15)

ResponseId
39346    20000.0
37549    11512.0
14673     8634.0
6942      6907.0
1566      5940.0
14613     3597.0
1241      3279.0
9825       719.0
38003       83.0
12281       14.0
25201        1.0
22246        1.0
1378         NaN
33453        NaN
55671        NaN
Name: Salary, dtype: float64

In [40]:
# for finding the median of the salary column
# median is the middle value of the sorted values, mean is the average of all the values
# mean is not usually used for salaries because it can be affected by outliers
df['Salary'].median()

65000.0

In [41]:
df.select_dtypes(include='number').median() # to get the median of all the numerical columns

CompTotal          110000.0
WorkExp                 9.0
JobSatPoints_1         10.0
JobSatPoints_4          0.0
JobSatPoints_5          0.0
JobSatPoints_6         20.0
JobSatPoints_7         15.0
JobSatPoints_8         10.0
JobSatPoints_9          5.0
JobSatPoints_10         0.0
JobSatPoints_11         0.0
Salary              65000.0
JobSat                  7.0
dtype: float64

In [42]:
df.describe() # to get the count (no. of non NaN rows), mean, std (standard deviation), min, 25%, 50% (median value), 75%, max of all the numerical columns

,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,Salary,JobSat
count,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

In [43]:
df['Salary'].count() # to get the count of non NaN values in the salary column
# ie the number of people who have entered their salary
# count function will not give the no. of individual values in a column (but the no. of rows with non NaN values)
# for counting the no. of individual values in a column use value_counts()

23435

In [44]:
df['Salary'].value_counts()

Salary
64444.0     321
53703.0     308
75184.0     230
85925.0     226
107406.0    208
           ...
34214.0       1
35640.0       1
37066.0       1
41342.0       1
12500.0       1
Name: count, Length: 6113, dtype: int64

In [45]:
df['Salary'].value_counts().sum()

23435

In [46]:
# for counting the no. of individual values in a column
df['Age'].value_counts()

Age
25-34 years old       23911
35-44 years old       14942
18-24 years old       14098
45-54 years old        6249
55-64 years old        2575
Under 18 years old     2568
65 years or older       772
Prefer not to say       322
Name: count, dtype: int64

In [47]:
df.sort_index(inplace=True)
df['PlatformAdmired'].value_counts().head()

PlatformAdmired
Amazon Web Services (AWS)                    6240
Microsoft Azure                              3572
Google Cloud                                 1692
Amazon Web Services (AWS);Microsoft Azure     905
Amazon Web Services (AWS);Google Cloud        797
Name: count, dtype: int64

In [48]:
df['PlatformAdmired'].value_counts(normalize=True) # to get the percentage of each value in the column

PlatformAdmired
Amazon Web Services (AWS)                                                                                                                                                                                                                                                                            0.198872
Microsoft Azure                                                                                                                                                                                                                                                                                      0.113841
Google Cloud                                                                                                                                                                                                                                                                                         0.053925
Amazon Web Services (AWS);Microsoft Azure                                                                                                                                                                                                                                                            0.028843
Amazon Web Services (AWS);Google Cloud                                                                                                                                                                                                                                                               0.025401
                                                                                                                                                                                                                                                                                                       ...
Alibaba Cloud;Amazon Web Services (AWS);Cloudflare;Colocation;Databricks;Digital Ocean;Firebase;Fly.io;Google Cloud;Heroku;Hetzner;IBM Cloud Or Watson;Linode, now Akamai;Managed Hosting;Microsoft Azure;Netlify;OpenShift;OpenStack;Oracle Cloud Infrastructure (OCI);OVH;PythonAnywhere;Render    0.000032
Amazon Web Services (AWS);Cloudflare;Heroku;Microsoft Azure;Netlify;Render;Vercel                                                                                                                                                                                                                    0.000032
Amazon Web Services (AWS);Vercel;Vultr                                                                                                                                                                                                                                                               0.000032
Amazon Web Services (AWS);Microsoft Azure;PythonAnywhere;Supabase                                                                                                                                                                                                                                    0.000032
PythonAnywhere;Render;Vercel                                                                                                                                                                                                                                                                         0.000032
Name: proportion, Length: 2556, dtype: float64

### Grouping

groupby : includes some combination of splitting the object, applying the function and combining the results

In [49]:
df['Country'].value_counts()

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Central African Republic                                    1
Equatorial Guinea                                           1
Niger                                                       1
Guinea                                                      1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

In [50]:
country_group = df.groupby(['Country']) # to group the data by the country column
# using groupby splits up all of the differences by country name

In [51]:
# country_group.get_group('India')  # give a warining (because this way is outdated)
country_group.get_group(('India',)) # to get the data of a particular group

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,Salary,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18,I am a developer by profession,18-24 years old,"Independent contractor, freelancer, or self-em...",R,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Coding sessions (live or recorded);How-t...,NaN,6,3,"Developer, front-end",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,NaN,Amazon Web Services (AWS);Digital Ocean;Fireba...,NaN,NaN,jQuery;Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,React Native,OpenGL;React Native,React Native,Docker;npm;Vite;Yarn,Docker;pnpm;Vite,Docker;Vite,VSCodium,VSCodium,VSCodium,Windows,Windows,Azure Devops,Azure Devops,Azure Devops,Google Meet;Microsoft Teams;Telegram;Whatsapp,Google Meet;Microsoft Teams,Google Meet;Microsoft Teams,ChatGPT,GitHub Copilot;Google Gemini,NaN,Stack Overflow;Stack Exchange,Less than once per month or monthly,Yes,Less than once per month or monthly,Quickly finding code solutions,Neutral,"No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,Replacing jobs without options for new employm...,Lack of executive buy-in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
59,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;Coding sessions (live or record...,NaN,4,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;JavaScript;Python;SQL,C++;HTML/CSS;Python,C++;HTML/CSS;Python,SQLite,NaN,NaN,NaN,NaN,NaN,Django;Node.js,Django,Django,Arduino,Arduino,Arduino,NaN,NaN,NaN,npm,NaN,NaN,Code::Blocks;PyCharm;Visual Studio Code,Code::Blocks;Visual Studio Code,Code::Blocks;Visual Studio Code,Android;Ubuntu;Windows,Windows,NaN,NaN,NaN,Discord;Telegram;Whatsapp,Whatsapp,Whatsapp,ChatGPT,GitHub Copilot;Google Gemini,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,Neutral,Yes,Favorable,Increase productivity;Greater efficiency;Make ...,Somewhat trust,Neither good or bad at handling complex tasks,Debugging and getting help;Search for answers,NaN,NaN,NaN,Search for answers,Debugging and getting help,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
76,I am learning to code,25-34 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,Online Courses or Certification;Coding Bootcamp,NaN,NaN,4,NaN,Designer,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript,Dart;Kotlin;Swift,NaN,MongoDB,NaN,NaN,Firebase;Heroku;VMware,Digital Ocean,NaN,Node.js;React,NaN,NaN,NaN,NaN,NaN,Flutter;Ionic;React Native,NaN,NaN,npm,NaN,NaN,Android Studio;IntelliJ IDEA;Notepad++;Sublime...,NaN,NaN,Android;Ubuntu;Windows,NaN,Asana;Clickup;Miro;Monday.com,Notion;Stack Overflow for Teams,NaN,Skype;Slack;Whatsapp;Zoom,Discord;Google Chat,NaN,Google Gemini,NaN,NaN,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,Quickly finding code solutions;Finding reliabl...,Neutral,"No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Replacing jobs without options for new employm...,Don’t trust the output or answers;Not everyone...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
90,I am learning to code,25-34 years old,"Employed, full-time",I,Apples,Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","School (i.e., University, College, etc);Online...",NaN,NaN,2,NaN,Security professional,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;SQL;Visual ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Managed Hosting;VMware,NaN,NaN,ASP.NET;CodeIgniter;Node.js;WordPress,CodeIgniter;Node.js,CodeIgniter;Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NumPy,NaN,NaN,npm,NaN,NaN,Nano;Netbeans;Notepad++;Sublime Text;Vim;Visua...,Nano;Notepad++;Visual Studio Code,Nano;Notepad++;Visual Studio Code,Debian;Ubuntu;Windows;Windows Subsystem for Li...,Debian;Ubuntu;Windows;Windows Subsystem for Li...,Stack Overflow for Teams,NaN,NaN,Cisco Webex Teams;Discord;Google Meet;Microsof...,Discord;Google Meet;Microsoft Teams;Telegram;W...,Discord;Google Meet;Microsoft Teams;Telegram;W...,ChatGPT;Snyk Code,ChatGPT;Snyk Code,ChatGPT;Snyk Code,Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Finding reliable guidance from community-vette...,"Yes, definitely","No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;R...,Not everyone uses them,Yes,Individual contributor,3.0,Agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Never,1-2 times a week,Never,60-120 minutes a day,Less than 15 minutes a day,None of these,Observability tools;Knowledge sharing community,Hybrid (on-prem and cloud),AI-powered search (free),Higher Education,80.0,90.0,90.0,50.0,70.0,50.0,50.0,50.0,80.0,Appropriate in length,Easy,NaN,8.0
97,I am a developer by profession,25-34 years old,"Employed, full-time",R,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,11,7,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,Bash/Shell (all shells);C#;JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.NET (5+) ;.NET MAUI,NaN,NaN,NuGet,NaN,NaN,Visual Studio;Visual Studio Code;Xcode,Rider,NaN,Android;Windows,Android;iOS;MacOS;Windows,Azure Devops,NaN,NaN,Microsoft Teams,NaN,NaN,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot;Google Gemini;Meta AI,ChatGPT;GitHub Copilot,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, somewhat",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Documenting code;Search for answe...,Learning about a codebase;Project planning;Deb...,NaN,Generating content or synthetic data,NaN,Writing code;Documenting code;Search for answers,NaN,NaN,Yes,Biased results that do not represent diverse v...,"AI tools lack context of codebase, internal a...",Yes,Individual contributor,7.0,Agree,Neither agree nor disagree,Disagree,Agree,Neither agree nor disagree,Agree,Agree,Agree,Strongly disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Amount of technical debt;Tracking my work;Show...,DevOps function;Developer portal or other cent...,Cloud only (single or multi-cloud),A coworker,Software Development,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Too long,Easy,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65340,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Social Media;How-to vi...,API document(s) and/or SDK document(s),4,2,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C#;C++;Go;HTML/CSS;JavaScript;Objective-C;Py...,NaN,NaN,Cassandra;Firebase Realtime Database;MariaDB;M...,NaN,NaN,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,Django;Flask;Next.js;Node.js;React,NaN,NaN,Arduino;Rasberry Pi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,Quickly finding code solutions;Finding reliabl...,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65384,I am learning to code,18-24 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,"School (i.e., University, College, etc)",NaN,NaN,9,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Exchange,Less than once per month or monthly,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65414,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Social Media;How-to videos;Video-based Online ...,NaN,3,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions,"No, not at all",Yes,Unsure,Increase productivity;Speed up learning;Make w...,Somewhat trust,Bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65416,I code primarily as a hobby,35-44 years old,I prefer not to say,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Stack Overflow;Social Media;Video-based ...,NaN,4,NaN,System administrator,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Engage with com...,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65429,I am a developer by profession,25-34 years old,"Employed, full-time",R,Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Other online ...,Technical documentation;Books;Interactive tuto...,API document(s) and/or SDK document(s);User gu...,4,7,"Developer, back-end","1,000 to 4,999 employees",I have some influence,Start a free trial;Ask developers I know/work ...,NaN,Integrated developer community;Frequent update...,India,INR\tIndian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions;Finding reliabl...,Neutral,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
# using filter (same as above) but when using groupby splits up all of the differences by country name
# filt = df['Country']=='India'
# df.loc[filt]

In [53]:
filt = df['Country']=='India'
df.loc[filt]['PlatformAdmired'].value_counts()
# these are the sesults for one specific country
# but with groupby object it will give the result for all of the country groups

PlatformAdmired
Amazon Web Services (AWS)                                                                                                          464
Microsoft Azure                                                                                                                    159
Google Cloud                                                                                                                        97
Firebase                                                                                                                            89
Amazon Web Services (AWS);Microsoft Azure                                                                                           85
                                                                                                                                  ...
Amazon Web Services (AWS);Cloudflare;Vultr                                                                                           1
Amazon Web Services (AWS);Cloudflare;Digital Ocean;Google Cloud;Linode, now Akamai;Managed Hosting;Microsoft Azure;Vercel;Vultr      1
Amazon Web Services (AWS);Vercel;Vultr                                                                                               1
Amazon Web Services (AWS);Firebase;Netlify;Vercel;VMware                                                                             1
Amazon Web Services (AWS);Cloudflare;Digital Ocean;Google Cloud;OpenStack                                                            1
Name: count, Length: 541, dtype: int64

In [54]:
country_group = df.groupby(['Country'])
country_group['PlatformAdmired'].value_counts()

Country      PlatformAdmired
Afghanistan  Amazon Web Services (AWS)                                                                                                                                                                                                                                                                                                                  6
             Alibaba Cloud                                                                                                                                                                                                                                                                                                                              1
             Alibaba Cloud;Amazon Web Services (AWS);Cloudflare;Colocation;Databricks;Digital Ocean;Firebase;Fly.io;Google Cloud;Heroku;Hetzner;IBM Cloud Or Watson;Linode, now Akamai;Managed Hosting;Microsoft Azure;Netlify;OpenShift;OpenStack;Oracle Cloud Infrastructure (OCI);OVH;PythonAnywhere;Render;Scaleway;Supabase;Vercel;VMware;Vultr    1
             Alibaba Cloud;Amazon Web Services (AWS);Colocation;Digital Ocean;Managed Hosting;Microsoft Azure;Netlify;OpenShift;OpenStack                                                                                                                                                                                                               1
             Amazon Web Services (AWS);Digital Ocean                                                                                                                                                                                                                                                                                                    1
                                                                                                                                                                                                                                                                                                                                                       ..
Zimbabwe     Microsoft Azure                                                                                                                                                                                                                                                                                                                            1
             Netlify                                                                                                                                                                                                                                                                                                                                    1
             Oracle Cloud Infrastructure (OCI);OVH                                                                                                                                                                                                                                                                                                      1
             Supabase                                                                                                                                                                                                                                                                                                                                   1
             Vultr                                                                                                                                                                                                                                                                                                                                      1
Name: count, Length: 8827, dtype: int64

In [55]:
# if we need to find it for a particular country
country_group['PlatformAdmired'].value_counts().loc['China']
# useful than using filter
# (because in filter, for different countries we need to change the filt, but here we only change the loc)

PlatformAdmired
Alibaba Cloud                               39
Cloudflare                                  20
Amazon Web Services (AWS)                   17
Alibaba Cloud;Cloudflare                     7
Cloudflare;Vercel                            7
                                            ..
OpenStack;VMware                             1
Oracle Cloud Infrastructure (OCI)            1
Oracle Cloud Infrastructure (OCI);VMware     1
Render;Supabase;Vercel                       1
Supabase;Vercel                              1
Name: count, Length: 75, dtype: int64

In [56]:
country_group['PlatformAdmired'].value_counts(normalize=True).loc['Germany'] # here we only change the loc for different country's data
# normalize=True can be used to get percentage

PlatformAdmired
Amazon Web Services (AWS)                     0.164662
Microsoft Azure                               0.125347
Hetzner                                       0.104995
Google Cloud                                  0.041628
Amazon Web Services (AWS);Microsoft Azure     0.028215
                                                ...
Oracle Cloud Infrastructure (OCI);Supabase    0.000463
Render                                        0.000463
Render;Supabase                               0.000463
Render;Vercel                                 0.000463
Vercel;VMware                                 0.000463
Name: proportion, Length: 369, dtype: float64

In [57]:
# for finding median salary by country
country_class = df.groupby(['Country']) # country_group can be used instead of creating a new groupby object
country_class['Salary'].median()

Country
Afghanistan                               3438.0
Albania                                  35341.0
Algeria                                   7120.0
Andorra                                 123517.0
Angola                                    1754.0
                                          ...
Venezuela, Bolivarian Republic of...     10800.0
Viet Nam                                 12288.5
Yemen                                     5333.0
Zambia                                    2280.0
Zimbabwe                                 18000.0
Name: Salary, Length: 185, dtype: float64

In [58]:
country_class['Salary'].median().loc['United States of America']

143000.0

### Aggregate function (agg())
used for running multilple aggregate functions in a group

In [59]:
# to run multiple aggregate functions on the group
# eg: to see the mean and median
country_class['Salary'].agg(['median','mean'])

                                        median           mean
Country
Afghanistan                             3438.0    5057.250000
Albania                                35341.0   39207.545455
Algeria                                 7120.0   91836.700000
Andorra                               123517.0  123517.000000
Angola                                  1754.0    1366.333333
...                                        ...            ...
Venezuela, Bolivarian Republic of...   10800.0   20137.371429
Viet Nam                               12288.5   18803.281250
Yemen                                   5333.0   16498.400000
Zambia                                  2280.0   17054.400000
Zimbabwe                               18000.0   29681.818182

[185 rows x 2 columns]

In [60]:
country_class['Salary'].agg(['median','mean']).loc['India']

median    16749.000000
mean      30513.611379
Name: India, dtype: float64

In [61]:
filt = df['Country']=='India'
df.loc[filt]['LanguageHaveWorkedWith'].str.contains('Python').sum()
# to find the no. of people we use sum() (it works on numbers as well as boolean)

2128

In [62]:
# country_class['LanguageHaveWorkedWith'].str.contains('Python').sum() # doesnt work with groups instead use apply
country_class['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python')).loc['India'].sum()

2128

In [63]:
country_class['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

### Q: To find percentage of people knowing python in all countries

In [64]:
# to find the percentage of people knowing python in all countries
country_respondents = df['Country'].value_counts()
country_respondents
# country_class['Country'].value_counts()

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Central African Republic                                    1
Equatorial Guinea                                           1
Niger                                                       1
Guinea                                                      1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

In [65]:
country_uses_python = country_class['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [66]:
# concatinating total participants from each country with total participants in each country who knows pyhton
python_df = pd.concat([country_respondents,country_uses_python], axis='columns')
python_df

,count,LanguageHaveWorkedWith
Country,,
United States of America,11095,6251
Germany,4947,2647
India,4231,2128
United Kingdom of Great Britain and Northern Ireland,3224,1638
Ukraine,2672,963
...,...,...
Central African Republic,1,1
Equatorial Guinea,1,0
Niger,1,1
Guinea,1,0
Solomon Islands,1,0

In [67]:
# to rename the columns since they are unrelated names
python_df.rename(columns={'count':'country_respondents', 'LanguageHaveWorkedWith':'country_uses_python'},inplace=True)
# python_df.columns = ['country_respondents', 'country_uses_python'] # this method can also be used to rename but all values must be provided
python_df

,country_respondents,country_uses_python
Country,,
United States of America,11095,6251
Germany,4947,2647
India,4231,2128
United Kingdom of Great Britain and Northern Ireland,3224,1638
Ukraine,2672,963
...,...,...
Central African Republic,1,1
Equatorial Guinea,1,0
Niger,1,1
Guinea,1,0
Solomon Islands,1,0

In [68]:
# for calculating the percentage (we add a new column for the percentage values)
python_df['percentagepy']= (country_uses_python/country_respondents)*100
python_df

,country_respondents,country_uses_python,percentagepy
Country,,,
United States of America,11095,6251,56.340694
Germany,4947,2647,53.507176
India,4231,2128,50.295438
United Kingdom of Great Britain and Northern Ireland,3224,1638,50.806452
Ukraine,2672,963,36.040419
...,...,...,...
Central African Republic,1,1,100.000000
Equatorial Guinea,1,0,0.000000
Niger,1,1,100.000000
Guinea,1,0,0.000000
Solomon Islands,1,0,0.000000

In [69]:
python_df.sort_values(by='percentagepy',ascending=False,inplace=True) # it also works without by=
python_df.head(25)

,country_respondents,country_uses_python,percentagepy
Country,,,
Niger,1,1,100.000000
Central African Republic,1,1,100.000000
Samoa,1,1,100.000000
Lesotho,1,1,100.000000
Saint Kitts and Nevis,1,1,100.000000
Dominica,1,1,100.000000
Chad,1,1,100.000000
Belize,2,2,100.000000
Brunei Darussalam,3,3,100.000000
Mauritania,5,4,80.000000
Liberia,4,3,75.000000
"Congo, Republic of the...",8,6,75.000000
Libyan Arab Jamahiriya,4,3,75.000000
Guyana,3,2,66.666667
Sierra Leone,3,2,66.666667
North Korea,3,2,66.666667
Democratic Republic of the Congo,3,2,66.666667
Monaco,3,2,66.666667
Bhutan,3,2,66.666667
Zimbabwe,26,17,65.384615
El Salvador,19,12,63.157895
Kuwait,8,5,62.500000
Singapore,177,110,62.146893
Israel,604,360,59.602649
South Korea,146,87,59.589041

In [70]:
python_df.loc['Japan']

country_respondents    288.000000
country_uses_python    167.000000
percentagepy            57.986111
Name: Japan, dtype: float64

# Cleaning Data

### Q: To calculate the average number of years of coding experience

In [71]:
df['YearsCode'].head(10)

ResponseId
1     NaN
2      20
3      37
4       4
5       9
6      10
7       7
8       1
9      20
10     15
Name: YearsCode, dtype: object

In [72]:
# df['YearsCode']=df['YearsCode'].astype(float) 
# # we get an error because of the 'Less than 1 year' value
df['YearsCode'].unique() # to get the unique values in the column
# here we see 'Less than 1 year' and 'More than 50 years' which are string value and cannot be converted to float

array([nan, '20', '37', '4', '9', '10', '7', '1', '15', '30', '31', '6',
       '12', '22', '5', '36', '25', '44', '24', '18', '3', '8',
       'More than 50 years', '11', '29', '40', '39', '2', '42', '34',
       '19', '35', '16', '33', '13', '23', '14', '28', '17', '21', '43',
       '46', '26', '32', '41', '45', '27', '38', '50', '48', '47',
       'Less than 1 year', '49'], dtype=object)

In [77]:
# so we eill reeplace these values with other values 
# (inplace=True cannot be used since it will be deprecated in the future versions of pandas)
df['YearsCode'] = df['YearsCode'].replace('Less than 1 year',0)
df['YearsCode'] = df['YearsCode'].replace('More than 50 years',51)
df['YearsCode'].unique()

array([nan, 20., 37.,  4.,  9., 10.,  7.,  1., 15., 30., 31.,  6., 12.,
       22.,  5., 36., 25., 44., 24., 18.,  3.,  8., 51., 11., 29., 40.,
       39.,  2., 42., 34., 19., 35., 16., 33., 13., 23., 14., 28., 17.,
       21., 43., 46., 26., 32., 41., 45., 27., 38., 50., 48., 47.,  0.,
       49.])

In [74]:
# since they are still objects (strings) we need to convert them to float 
df['YearsCode']=df['YearsCode'].astype(float)

In [75]:
df['YearsCode'].mean()

14.197497870350265

In [76]:
df['YearsCode'].agg(['mean','median'])

mean      14.197498
median    11.000000
Name: YearsCode, dtype: float64