In [2]:
person = {
    "first": "Corey", 
    "last": "Schafer", 
    "email": "CoreyMSchafer@gmail.com"
}

In [3]:
people = {
    "first": ["Corey"], 
    "last": ["Schafer"], 
    "email": ["CoreyMSchafer@gmail.com"]
}

In [4]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [5]:
people.get("email")

['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(people) # converts a dictionary into Data Frame

In [8]:
df # Data Frame is a 2-D array

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

Accessing Columns

In [9]:
df['email'] # Gives a series (1-D array) of email along with an index

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [10]:
df.email # dot notation can also be used (unless the variable name is not a method name like count)

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [11]:
type(df['email'])  # shows the type (here series means a 1-D array)

pandas.core.series.Series

In [12]:
# to access multiple locations
df[['last','email']]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [13]:
type(df[['last','email']])

pandas.core.frame.DataFrame

In [14]:
# to access columns
df.columns

Index(['first', 'last', 'email'], dtype='object')

Accessing rows and columns using loc & iloc

In [15]:
# to access rows we use loc and iloc (integer location)
df.iloc[0] # gives the 0th row

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: object

In [16]:
# to access multiple rows
df.iloc[[0,2]] # returns the 0th and 2nd rows

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@email.com

In [17]:
# to access rows along with specific column
df.iloc[[0,1],2] # here 2 is the index for email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: object

In [18]:
# to access specific rows and specific columns
df.iloc[[0,1],[1,2]]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com

In [19]:
df.loc[0]

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: object

In [20]:
df.loc[[0,1]]

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [21]:
df.loc[[0,1],'email'] # in loc we can specify the column by name and not index

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: object

In [22]:
df.loc[[0,1],['first','email']] # to access mupltiple rows and columns (in the order specified in this code)

   first                    email
0  Corey  CoreyMSchafer@gmail.com
1   Jane        JaneDoe@email.com

In [25]:
# to conver series to data frame
df['first'].to_frame()

   first
0  Corey
1   Jane
2   John

In [27]:
# to convert a data frame to series (squeeze())
df['first'].to_frame().squeeze()

0    Corey
1     Jane
2     John
Name: first, dtype: object