In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   first   3 non-null      object
 1   last    3 non-null      object
 2   email   3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

Updating Columns

In [6]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [7]:
# to change the column names
df.columns = ['first name', 'last name', 'email']
df

  first name last name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [8]:
# for lower case; for upper use upper()
df.columns = [x.lower() for x in df.columns]
df.columns

Index(['first name', 'last name', 'email'], dtype='object')

In [9]:
# to replace (space with underscore)
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

To change only specific columns

In [10]:
# to change the column names make a dictionary with current names as keys and new names as values
df.rename(columns={'first_name':'first','last_name':'last'}, inplace=True)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

Updating the data in the rows

In [11]:
df.loc[2] = df.loc[2].str.replace('Doe','Smith')
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JohnSmith@email.com

In [12]:
# or make a list of the rows you want to change
df.loc[2]=['John','Smith','JohnSmith@gmail.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JohnSmith@gmail.com

In [13]:
# or to only cahnge specific data values
df.loc[2,['last','email']] = ['Dalton','JohnDalton@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John   Dalton     JohnDalton@email.com

In [14]:
# to change a single value (no need for a list)
df.loc[2,'last'] = 'Doe'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe     JohnDalton@email.com

In [15]:
# also can use at instead of loc
df.at[2,'last'] = 'Dalton'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John   Dalton     JohnDalton@email.com

In [16]:
filt = (df['last']=='Dalton')
df[filt]['last'] = 'Doe' # this will give a warning (and not change the value) because it is not clear if you want to change the original df or a copy of it

C:\Users\aswan\AppData\Local\Temp\ipykernel_11012\1413082805.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[filt]['last'] = 'Doe' # this will give a warning (and not change the value) because it is not clear if you want to change the original df or a copy of it

In [17]:
df  # the value is not changed
# ie, when you need to change a value in a df, use loc or at (and not the filter method)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John   Dalton     JohnDalton@email.com

In [18]:
# instead of using loc or at, you can use the .loc method with the filter
filt = (df['last']=='Dalton')
df.loc[filt, 'last'] = 'Doe'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe     JohnDalton@email.com

In [19]:
df['email'].str.lower() # no change to df since not assigned

0    coreymschafer@gmail.com
1          janedoe@email.com
2       johndalton@email.com
Name: email, dtype: object

In [20]:
df['email'] = df['email'].str.lower()
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John      Doe     johndalton@email.com

# apply, map, applymap,  replace

### apply: 
running apply on a series applies a function to every value in the series and <br>
running apply to a data frame applies a function to every series in the data frame

running apply on a series

In [21]:
# apply : to apply a function to a series (also used to update values as well)
df['email'].apply(len)

0    23
1    17
2    20
Name: email, dtype: int64

In [22]:
def update_email(email):
    return email.upper()   # value must be returned

In [23]:
df['email'].apply(update_email) # no need to use paranthesis for the function

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2       JOHNDALTON@EMAIL.COM
Name: email, dtype: object

In [24]:
df['email'] = df['email'].apply(update_email)
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane      Doe        JANEDOE@EMAIL.COM
2   John      Doe     JOHNDALTON@EMAIL.COM

In [25]:
# for shorter functions, use lambda functions
# lammbda functions are anonymous functions (ie, functions without a name)
df['email'] = df['email'].apply(lambda x: x.lower()) # syntax no_name_function : return_value
df 
# lambda functions can aslo be used with numbers to run calculations

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John      Doe     johndalton@email.com

In [26]:
df['email'].apply(len)

0    23
1    17
2    20
Name: email, dtype: int64

running apply to a dataframe

In [27]:
df.apply(len) # this will return the number of rows in each column
# this is because the apply function is applied to each series in the df (ie, each column) is, it says that first has 3 values, last has 3 values, email has 3 values
# (ie, counted verticlly)

first    3
last     3
email    3
dtype: int64

In [28]:
len(df['email']) # this will return the number of values in the email column

3

In [29]:
# to apply the apply function to each row, use the axis parameter
df.apply(len,axis='columns') # default value of axis is rows
# this will return the number of columns in each row (ie, counted horizontally)

0    3
1    3
2    3
dtype: int64

In [30]:
# series objects has a min method
df.apply(pd.Series.min) # this will return the min value in each column (ie, here in alphabetical order)
# if used in numerical data, it will return the min value in each column

# we can use extra attribute axis, 
# axis=0 or axis='index' for column wise & 
# axis=1 or axis='columns' for row wise
df.apply(pd.Series.min, axis='index')

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: object

In [31]:
# same as above
df.apply(lambda x: x.min()) # this x here is a series not a value (and series have a min method)

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: object

### applymap (not used, map is used instead):
apply a function to every individual element in the data frame (only works on data frames and not on series)

In [32]:
df.applymap(len)

C:\Users\aswan\AppData\Local\Temp\ipykernel_11012\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first  last  email
0      5     7     23
1      4     3     17
2      4     3     20

In [33]:
df.applymap(str.lower)

C:\Users\aswan\AppData\Local\Temp\ipykernel_11012\357608748.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(str.lower)

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@email.com
2   john      doe     johndalton@email.com

In [34]:
df.map(str.lower)

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@email.com
2   john      doe     johndalton@email.com

### map:
used for substituting each value in a series with another value (works on a series and data frames) <br>
when used with series: applies a function to each element in a Series (a single column). <br>
when applied with data frames: applies a function to each element in an entire DataFrame (multiple columns).(similar to applymap)

In [35]:
df['first'].map({'Corey':'Chris','Jane':'Mary'}) # this will change only the values that are in the dictionary (ie, it will change Corey to Chris and Jane to Mary) 
#other values (values not substituted) will become NaN

0    Chris
1     Mary
2      NaN
Name: first, dtype: object

### replace:
similar to map but does not give NaN values for data values which wasn't substituted

In [36]:
df['first'].replace({'Corey':'Chris','Jane':'Mary'}) # this will change only the values that are in the dictionary (ie, it will change Corey to Chris and Jane to Mary) other values will remain the same

0    Chris
1     Mary
2     John
Name: first, dtype: object

In [37]:
# to set the values in the df to the new values
df['first'] = df['first'].replace({'Corey':'Chris','Jane':'Mary'})
df

   first     last                    email
0  Chris  Schafer  coreymschafer@gmail.com
1   Mary      Doe        janedoe@email.com
2   John      Doe     johndalton@email.com